-- AlterTable
ALTER TABLE "User" ALTER COLUMN "discord" DROP NOT NULL,
ALTER COLUMN "discord" DROP DEFAULT,
ALTER COLUMN "instagram" DROP NOT NULL,
ALTER COLUMN "instagram" DROP DEFAULT,
ALTER COLUMN "mc_username" DROP NOT NULL,
ALTER COLUMN "mc_username" DROP DEFAULT;
